# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-04 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fresh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='zipcode',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
